In [1]:
#import lib...
import pandas as pd

In [2]:
#load csv files

In [4]:
employees = pd.read_csv(r"C:\HR Analysis\data\employee_survey_data.csv")

In [5]:
employees.head()

   EmployeeID  EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
0           1                      3.0              4.0              2.0
1           2                      3.0              2.0              4.0
2           3                      2.0              2.0              1.0
3           4                      4.0              4.0              3.0
4           5                      4.0              1.0              3.0

In [6]:
#correct the file name to work  with sql

In [7]:
employees.columns = ['employee_id',	'environment_satisfaction',	'job_satisfaction',	'work_life_balance']

In [8]:
#handeling null values

In [9]:
employees.isnull().sum()

employee_id                  0
environment_satisfaction    25
job_satisfaction            20
work_life_balance           38
dtype: int64

In [10]:
employees['environment_satisfaction'] = employees['environment_satisfaction'].fillna(employees['environment_satisfaction'].median())
employees['job_satisfaction'] = employees['job_satisfaction'].fillna(employees['job_satisfaction'].median())
employees['work_life_balance'] = employees['work_life_balance'].fillna(employees['work_life_balance'].median())

In [11]:
employees = employees.astype({'environment_satisfaction': 'int',	'job_satisfaction': 'int',	'work_life_balance': 'int'})

In [12]:
#employees[['EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance']] = employees[['EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance']].astype(int)

In [13]:
employees.dtypes

employee_id                 int64
environment_satisfaction    int64
job_satisfaction            int64
work_life_balance           int64
dtype: object

In [14]:
#2nd Data set

In [15]:
general_data = pd.read_csv(r"C:\HR Analysis\data\general_data.csv")

In [16]:
general_data.head()
#general_data.info()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [17]:
#3rd data set

In [18]:
manager_sur = pd.read_csv(r'C:\HR Analysis\data\manager_survey_data.csv')

In [19]:
manager_sur.head(10)

   EmployeeID  JobInvolvement  PerformanceRating
0           1               3                  3
1           2               2                  4
2           3               3                  3
3           4               2                  3
4           5               3                  3
5           6               3                  3
6           7               3                  4
7           8               3                  4
8           9               3                  4
9          10               3                  3

In [20]:
manager_sur.dtypes

EmployeeID           int64
JobInvolvement       int64
PerformanceRating    int64
dtype: object

In [21]:
#checking null and handling null values

In [22]:
employees.isnull().sum()

employee_id                 0
environment_satisfaction    0
job_satisfaction            0
work_life_balance           0
dtype: int64

In [23]:
manager_sur.isnull().sum()

EmployeeID           0
JobInvolvement       0
PerformanceRating    0
dtype: int64

In [24]:
general_data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [25]:
general_data['NumCompaniesWorked'] = general_data['NumCompaniesWorked'].fillna(0)

In [26]:
general_data['TotalWorkingYears'] = general_data['TotalWorkingYears'].fillna(general_data['TotalWorkingYears'].median())

In [27]:
general_data.isnull().sum()

Age                        0
Attrition                  0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
EmployeeCount              0
EmployeeID                 0
Gender                     0
JobLevel                   0
JobRole                    0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
Over18                     0
PercentSalaryHike          0
StandardHours              0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [28]:
general_data.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeID                   int64
Gender                      object
JobLevel                     int64
JobRole                     object
MaritalStatus               object
MonthlyIncome                int64
NumCompaniesWorked         float64
Over18                      object
PercentSalaryHike            int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears          float64
TrainingTimesLastYear        int64
YearsAtCompany               int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [29]:
#Correcting data type

In [30]:
general_data['NumCompaniesWorked'] = general_data['NumCompaniesWorked'].astype(int)
general_data['TotalWorkingYears'] = general_data['TotalWorkingYears'].astype(int)

In [31]:
general_data.dtypes

Age                         int64
Attrition                  object
BusinessTravel             object
Department                 object
DistanceFromHome            int64
Education                   int64
EducationField             object
EmployeeCount               int64
EmployeeID                  int64
Gender                     object
JobLevel                    int64
JobRole                    object
MaritalStatus              object
MonthlyIncome               int64
NumCompaniesWorked          int64
Over18                     object
PercentSalaryHike           int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [32]:
#Delete some column those are not required for analysis

In [33]:
general_data = general_data.drop(columns=['EmployeeCount', 'Over18', 'StandardHours'])

In [34]:
general_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      4410 non-null   int64
 1   Attrition                4410 non-null   object
 2   BusinessTravel           4410 non-null   object
 3   Department               4410 non-null   object
 4   DistanceFromHome         4410 non-null   int64
 5   Education                4410 non-null   int64
 6   EducationField           4410 non-null   object
 7   EmployeeID               4410 non-null   int64
 8   Gender                   4410 non-null   object
 9   JobLevel                 4410 non-null   int64
 10  JobRole                  4410 non-null   object
 11  MaritalStatus            4410 non-null   object
 12  MonthlyIncome            4410 non-null   int64
 13  NumCompaniesWorked       4410 non-null   int64
 14  PercentSalaryHike        4410 non-null   int64
 15  StockOptionLevel         4410 non-null   int64
 16  TotalWorkingYears        4410 non-null   int64
 17  TrainingTimesLastYear    4410 non-null   int64
 18  YearsAtCompany           4410 non-null   int64
 19  YearsSinceLastPromotion  4410 non-null   int64
 20  YearsWithCurrManager     4410 non-null   int64
dtypes: int64(14), object(7)
memory usage: 723.6+ KB

In [35]:
#correct column name

In [36]:
general_data.columns = [
    'age', 'attrition', 'business_travel', 'department',
    'distance_from_home', 'education', 'education_field',
    'employee_id', 'gender', 'job_level', 'job_role',
    'marital_status', 'monthly_income', 'num_companies_worked',
    'percent_salary_hike', 'stock_option_level', 'total_working_years',
    'training_times_last_year', 'years_at_company',
    'years_since_last_promotion', 'years_with_curr_manager'
]

In [37]:
general_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         4410 non-null   int64
 1   attrition                   4410 non-null   object
 2   business_travel             4410 non-null   object
 3   department                  4410 non-null   object
 4   distance_from_home          4410 non-null   int64
 5   education                   4410 non-null   int64
 6   education_field             4410 non-null   object
 7   employee_id                 4410 non-null   int64
 8   gender                      4410 non-null   object
 9   job_level                   4410 non-null   int64
 10  job_role                    4410 non-null   object
 11  marital_status              4410 non-null   object
 12  monthly_income              4410 non-null   int64
 13  num_companies_worked        4410 non-null   int64
 14  percent_salary_hike         4410 non-null   int64
 15  stock_option_level          4410 non-null   int64
 16  total_working_years         4410 non-null   int64
 17  training_times_last_year    4410 non-null   int64
 18  years_at_company            4410 non-null   int64
 19  years_since_last_promotion  4410 non-null   int64
 20  years_with_curr_manager     4410 non-null   int64
dtypes: int64(14), object(7)
memory usage: 723.6+ KB

In [38]:
manager_sur.columns = ['employee_id', 'job_involvement', 'performance_rating']

In [39]:
manager_sur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         4410 non-null   int64
 1   job_involvement     4410 non-null   int64
 2   performance_rating  4410 non-null   int64
dtypes: int64(3)
memory usage: 103.5 KB

In [40]:
employees.columns = ['employee_id',	'environment_satisfaction',	'job_satisfaction',	'work_life_balance']

In [41]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               4410 non-null   int64
 1   environment_satisfaction  4410 non-null   int64
 2   job_satisfaction          4410 non-null   int64
 3   work_life_balance         4410 non-null   int64
dtypes: int64(4)
memory usage: 137.9 KB

In [42]:
#clened and corrected formate and ready for analysis now connecting to the postgres

In [43]:
import psycopg2
from sqlalchemy import create_engine
import pandas as pd

# Connect to PostgreSQL
engine = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/hr_analytics")

#load to postgres

general_data.to_sql('general_data', engine, if_exists='replace', index=False)
employees.to_sql('employees', engine, if_exists='replace', index=False)
manager_sur.to_sql('manager_sur', engine, if_exists='replace', index=False)


# Test query
df = pd.read_sql("SELECT * FROM general_data LIMIT 5;", engine)
print(df)

InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table general_data because other objects depend on it
DETAIL:  view hr_full_data depends on table general_data
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL:
DROP TABLE general_data]
(Background on this error at: https://sqlalche.me/e/20/2j85)